// <auto-generated />
using System;
using KnightOnline.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnightOnline.Server.Migrations
{
    [DbContext(typeof(KnightDbContext))]
    [Migration("20260804081708_StarterTutorialVerticalSlice")]
    partial class StarterTutorialVerticalSlice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<byte>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("NormalizedUsername")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("AccountKey")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasFilter("\"normalized_username\" IS NOT NULL");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterAppearanceEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<string>("SlotDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slot_definition_id");

                    b.Property<string>("AppearanceDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("appearance_definition_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CharacterId", "SlotDefinitionId");

                    b.ToTable("character_appearances", (string)null);
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterCreationRequestEntity", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_code");

                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("result_message");

                    b.HasKey("RequestId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_creation_requests", (string)null);
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("BodyTypeDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("body_type_definition_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentClassDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_class_definition_id");

                    b.Property<string>("CurrentMapDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_map_definition_id");

                    b.Property<string>("CurrentSpawnPointId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_spawn_point_id");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("normalized_name");

                    b.Property<float>("PositionX")
                        .HasColumnType("real")
                        .HasColumnName("position_x");

                    b.Property<float>("PositionY")
                        .HasColumnType("real")
                        .HasColumnName("position_y");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("server_id");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer")
                        .HasColumnName("slot_index");

                    b.Property<long>("TotalExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_experience");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("AccountId", "ServerId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("characters", null, t =>
                        {
                            t.HasCheckConstraint("ck_characters_level_positive", "\"level\" >= 1");

                            t.HasCheckConstraint("ck_characters_slot_index", "\"slot_index\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_characters_total_experience_nonnegative", "\"total_experience\" >= 0");
                        });
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterProgressionGrantEntity", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<long>("AppliedExperience")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_experience");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("integer")
                        .HasColumnName("level_after");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("integer")
                        .HasColumnName("level_before");

                    b.Property<long>("RequestedExperience")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_experience");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<long>("TotalExperienceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("total_experience_after");

                    b.HasKey("RequestId");

                    b.HasIndex("CharacterId", "CreatedAtUtc");

                    b.ToTable("character_progression_grants", (string)null);
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterTutorialProgressEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<string>("TutorialDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tutorial_definition_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<bool?>("ContinueChoice")
                        .HasColumnType("boolean")
                        .HasColumnName("continue_choice");

                    b.Property<string>("CurrentStepDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_step_definition_id");

                    b.Property<int>("ObjectiveProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("objective_progress");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<byte>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CharacterId", "TutorialDefinitionId");

                    b.ToTable("character_tutorial_progress", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_tutorial_progress_objective_nonnegative", "\"objective_progress\" >= 0");
                        });
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.RefreshSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id_hash");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AccountId", "DeviceIdHash");

                    b.ToTable("refresh_sessions", (string)null);
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterAppearanceEntity", b =>
                {
                    b.HasOne("KnightOnline.Server.Persistence.Entities.CharacterEntity", "Character")
                        .WithMany("Appearances")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterCreationRequestEntity", b =>
                {
                    b.HasOne("KnightOnline.Server.Persistence.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnightOnline.Server.Persistence.Entities.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterEntity", b =>
                {
                    b.HasOne("KnightOnline.Server.Persistence.Entities.AccountEntity", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterProgressionGrantEntity", b =>
                {
                    b.HasOne("KnightOnline.Server.Persistence.Entities.CharacterEntity", "Character")
                        .WithMany("ProgressionGrants")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterTutorialProgressEntity", b =>
                {
                    b.HasOne("KnightOnline.Server.Persistence.Entities.CharacterEntity", "Character")
                        .WithMany("TutorialProgress")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.RefreshSessionEntity", b =>
                {
                    b.HasOne("KnightOnline.Server.Persistence.Entities.AccountEntity", "Account")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.AccountEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("RefreshSessions");
                });

            modelBuilder.Entity("KnightOnline.Server.Persistence.Entities.CharacterEntity", b =>
                {
                    b.Navigation("Appearances");

                    b.Navigation("ProgressionGrants");

                    b.Navigation("TutorialProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
