namespace KnightOnline.Client.Shared.Packets
{
    public enum PacketType : byte
    {
        Unknown = 0,
        ConnectRequest = 1,
        ConnectResponse = 2,
        CreateCharacterRequest = 3,
        CreateCharacterResponse = 4,
        ListCharactersRequest = 5,
        ListCharactersResponse = 6,
        ListMonstersRequest = 7,
        ListMonstersResponse = 8,
        AttackMonsterRequest = 9,
        MonsterHealthChanged = 10,
        MonsterDied = 11,
        MonsterRespawned = 12,
        SelectCharacterRequest = 13,
        SelectCharacterResponse = 14,
        PlayerMoveInput = 15,
        AttackResult = 16,
        ForcedDisconnect = 17,
        CreateGuestRequest = 18,
        CreateGuestResponse = 19,
        ResumeAccountRequest = 20,
        ResumeAccountResponse = 21,
        LoginRequest = 22,
        LoginResponse = 23,
        LeaveAccountSessionRequest = 24,
        LeaveAccountSessionResponse = 25,
        BeginRegistrationRequest = 26,
        BeginRegistrationResponse = 27,
        CompleteDevelopmentRegistrationRequest = 28,
        CompleteDevelopmentRegistrationResponse = 29,
        GetCharacterCreationCatalogRequest = 30,
        GetCharacterCreationCatalogResponse = 31,
        CheckCharacterNameRequest = 32,
        CheckCharacterNameResponse = 33,
        AccountSessionHeartbeatRequest = 34,
        AccountSessionHeartbeatResponse = 35,
        EnterWorldRequest = 36,
        EnterWorldResponse = 37,
        PlayerPositionSnapshot = 38,
        CharacterProgressionChanged = 39,
    }
}
